using System;

namespace ZebraSDK
{
	public enum ZplPrintMode {
		PL_PRINT_MODE_REWIND,
		PL_PRINT_MODE_PEEL_OFF,
		PL_PRINT_MODE_TEAR_OFF,
		PL_PRINT_MODE_CUTTER,
		PL_PRINT_MODE_APPLICATOR,
		PL_PRINT_MODE_DELAYED_CUT,
		PL_PRINT_MODE_LINERLESS_PEEL,
		PL_PRINT_MODE_LINERLESS_REWIND,
		PL_PRINT_MODE_PARTIAL_CUTTER,
		PL_PRINT_MODE_RFID,
		PL_PRINT_MODE_KIOSK,
		PL_PRINT_MODE_UNKNOWN
	}

	public enum ZebraErrorCode  {
		EBRA_ERROR_NO_CONNECTION,
		EBRA_ERROR_WRITE_FAILURE,
		EBRA_ERROR_READ_FAILURE,
		EBRA_UNKNOWN_PRINTER_LANGUAGE,
		EBRA_MALFORMED_NETWORK_DISCOVERY_ADDRESS,
		EBRA_NETWORK_ERROR_DURING_DISCOVERY,
		EBRA_INVALID_DISCOVERY_HOP_COUNT,
		EBRA_MALFORMED_PRINTER_STATUS_RESPONSE,
		EBRA_INVALID_FORMAT_NAME,
		EBRA_BAD_FILE_DIRECTORY_ENTRY,
		EBRA_MALFORMED_FORMAT_FIELD_NUMBER,
		EBRA_INVALID_PRINTER_LANGUAGE,
		EBRA_INVALID_FILE_NAME,
		EBRA_INVALID_PRINTER_DRIVE_LETTER
	}

	public enum PrinterLanguage  {
		ZPL,
		CPCL
	}
}

